language: cpp
env:
  global:
   #- DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
sudo: true
#dist: "xenial"
install:
   - |
     if [ $TRAVIS_OS_NAME = linux ]; then
      sudo apt-get install libboost-dev libssl-dev libxml2-dev bluez zlib1g-dev cmake-data
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 20
     fi
     if [ $TRAVIS_OS_NAME = osx ]; then
      brew install boost
     fi
     pwd
     cd ..
     pwd
script:
   - g++ -v
   - cd ${TRAVIS_BUILD_DIR}
   - pwd
   - mkdir -p build
   - cd build
   - cmake ..
   - make